import type { AtlasEdge, AtlasNode, GitlabIssue } from './atlas-types'

export const ATLAS_NODES: AtlasNode[] = [
  // ---------------- CORE ----------------
  {
    id: 'sap-s4',
    label: 'SAP S/4HANA',
    kind: 'erp',
    status: 'prod',
    domain: 'Core SAP',
    owner: 'Equipo Basis',
    description:
      'ERP central, Private Cloud Edition. Fuente de verdad de maestros, pedidos, facturación y finanzas.',
    x: 0,
    y: 0,
    tech: ['S/4HANA 2023', 'HANA DB', 'ABAP RAP'],
    sla: '99.9%',
    volume: '~1.2M docs/mes',
  },
  {
    id: 'web-dispatcher',
    label: 'SAP Web Dispatcher',
    kind: 'dispatcher',
    status: 'prod',
    domain: 'Core SAP',
    owner: 'Equipo Basis',
    description:
      'Punto de entrada HTTP(S) para interfaces externas que no pasan por CPI. Balanceo y terminación TLS.',
    x: -430,
    y: -230,
    tech: ['SAP Web Dispatcher 7.89'],
    sla: '99.9%',
  },
  {
    id: 'sap-api-salesorder',
    label: 'API_SALES_ORDER_SRV',
    kind: 'api',
    status: 'prod',
    domain: 'Core SAP',
    owner: 'Equipo SD',
    description: 'API OData estándar de SAP para creación y consulta de pedidos de venta.',
    x: 250,
    y: 150,
    parentId: 'sap-s4',
    tech: ['OData V2'],
    endpoints: [
      {
        id: 'so-post',
        method: 'POST',
        path: '/A_SalesOrder',
        target: 'SAP S/4HANA',
        scope: 'sap',
        avgMs: 840,
        note: 'Alta de pedido de venta.',
        auth: 'OAuth2 / x-csrf-token',
        headers: { 'Content-Type': 'application/json', 'x-csrf-token': '<token>' },
        envUrls: [
          { env: 'Producción', baseUrl: 'https://sap-prod.grupocepas.com/sap/opu/odata/sap/API_SALES_ORDER_SRV' },
          { env: 'QA', baseUrl: 'https://sap-qa.grupocepas.com/sap/opu/odata/sap/API_SALES_ORDER_SRV' },
        ],
        variants: [
          {
            orderType: 'Pedido estándar (OR)',
            requestBody:
              '{\n  "SalesOrderType": "OR",\n  "SoldToParty": "0001002345",\n  "SalesOrganization": "AR10",\n  "DistributionChannel": "10",\n  "OrganizationDivision": "00",\n  "to_Item": [\n    { "Material": "100023", "RequestedQuantity": "12" }\n  ]\n}',
            responseBody: '{\n  "d": { "SalesOrder": "0000778812", "SalesOrderType": "OR" }\n}',
          },
        ],
      },
      {
        id: 'so-get',
        method: 'GET',
        path: '/A_SalesOrder(:id)',
        target: 'SAP S/4HANA',
        scope: 'sap',
        avgMs: 210,
        note: 'Consulta de pedido por ID.',
      },
      {
        id: 'so-patch',
        method: 'PATCH',
        path: '/A_SalesOrderItem',
        target: 'SAP S/4HANA',
        scope: 'sap',
        avgMs: 390,
        note: 'Modificación de posición del pedido.',
      },
    ],
  },
  {
    id: 'sap-toolkit',
    label: 'Google BQ Toolkit for SAP',
    kind: 'loader',
    status: 'prod',
    domain: 'Datos & Analytics',
    owner: 'Data Platform',
    description:
      'Toolkit de Google que replica tablas de SAP hacia BigQuery mediante extracción CDC/SLT.',
    x: -170,
    y: 300,
    tech: ['BQ Connector', 'SLT', 'CDC'],
    volume: '410 tablas',
  },

  // ---------------- INTEGRACIÓN ----------------
  {
    id: 'cpi',
    label: 'SAP CPI',
    kind: 'middleware',
    status: 'prod',
    domain: 'Integración',
    owner: 'Equipo Integración',
    description:
      'Cloud Platform Integration. Todo el tráfico API (interno y externo) pasa por acá: mapeos, ruteo, auth y logging.',
    x: 380,
    y: -60,
    tech: ['SAP Integration Suite', 'Groovy', 'OAuth2'],
    sla: '99.5%',
    volume: '~2.4M msg/mes',
    gitlab: {
      id: 'gl-cpi',
      path: 'integraciones/cpi-iflows',
      branch: 'main',
      lastPipeline: 'passed',
      openIssues: 6,
    },
  },
  {
    id: 'ext-aduana',
    label: 'Portal Aduana (Externo)',
    kind: 'external',
    status: 'prod',
    domain: 'Integración',
    owner: 'Tercero',
    description:
      'Interfaz externa que consume SAP directamente por Web Dispatcher, sin pasar por CPI. Legado.',
    x: -760,
    y: -330,
    country: 'AR',
    tech: ['SOAP', 'mTLS'],
  },
  {
    id: 'ext-courier',
    label: 'Courier API (Externo)',
    kind: 'external',
    status: 'prod',
    domain: 'Integración',
    owner: 'Tercero',
    description: 'Proveedor logístico externo, consume y publica vía CPI con API Key rotativa.',
    x: 730,
    y: -300,
    country: 'CL',
    tech: ['REST', 'API Key'],
  },

  // ---------------- GCC ----------------
  {
    id: 'gcc',
    label: 'GCC',
    kind: 'interface',
    status: 'prod',
    domain: 'Aplicaciones',
    owner: 'Equipo GCC',
    description:
      'Global Commercial Center. Interfaz comercial de la compañía. Extrae datos desde SQL e inyecta transacciones hacia SAP vía CPI.',
    x: 720,
    y: 120,
    tech: ['Next.js', '.NET 8', 'SQL Server'],
    sla: '99.5%',
    volume: '~18k pedidos/mes',
    environments: [
      { name: 'Producción', server: 'gcc-prod-01.cepas.local', url: 'https://gcc.grupocepas.com', status: 'ok' },
      { name: 'Staging', server: 'gcc-stg-01.cepas.local', url: 'https://gcc.stg.grupocepas.com', status: 'ok' },
      { name: 'QA', server: 'gcc-qa-01.cepas.local', status: 'degradado' },
    ],
    gitlab: {
      id: 'gl-gcc',
      path: 'gcc/gcc-platform',
      branch: 'develop',
      lastPipeline: 'passed',
      openIssues: 9,
      closedIssues: 14,
      sprint: 'Sprint 24',
      syncedAt: 'hace 8 min',
    },
  },

  // rama de inyección: Web de Pedidos
  {
    id: 'wp',
    label: 'Web de Pedidos',
    kind: 'interface',
    status: 'prod',
    domain: 'Aplicaciones',
    owner: 'Equipo GCC',
    description:
      'Rama de inyección de GCC. Permite a la fuerza de ventas cargar pedidos que viajan a SAP por CPI.',
    x: 1090,
    y: -110,
    parentId: 'gcc',
    country: 'AR',
    tech: ['Next.js', 'Node', 'Redis'],
    volume: '~620 pedidos/día',
    environments: [
      { name: 'Producción', server: 'wp-prod-ar.cepas.local', url: 'https://pedidos.grupocepas.com', status: 'ok' },
      { name: 'Staging', server: 'wp-stg-ar.cepas.local', url: 'https://pedidos.stg.grupocepas.com', status: 'ok' },
    ],
    gitlab: {
      id: 'gl-wp',
      path: 'gcc/web-pedidos',
      branch: 'release/2.4',
      lastPipeline: 'failed',
      openIssues: 7,
      closedIssues: 11,
      sprint: 'Sprint 24',
      syncedAt: 'hace 8 min',
    },
  },
  {
    id: 'wp-front',
    label: 'WP · Front',
    kind: 'front',
    status: 'prod',
    domain: 'Aplicaciones',
    owner: 'Equipo GCC',
    description: 'SPA de carga de pedidos con validación de stock y precios en tiempo real.',
    x: 1420,
    y: -260,
    parentId: 'wp',
    tech: ['Next.js 15', 'React 19', 'Tailwind'],
    gitlab: {
      id: 'gl-wp-front',
      path: 'gcc/web-pedidos-front',
      branch: 'release/2.4',
      lastPipeline: 'passed',
      openIssues: 4,
    },
  },
  {
    id: 'wp-gw',
    label: 'WP · Gateway',
    kind: 'gateway',
    status: 'prod',
    domain: 'Aplicaciones',
    owner: 'Equipo GCC',
    description: 'API Gateway: auth Entra ID, rate limit, agregación y trazabilidad de requests.',
    x: 1420,
    y: -110,
    parentId: 'wp',
    tech: ['Kong', 'JWT / Entra ID'],
    gitlab: {
      id: 'gl-wp-gw',
      path: 'gcc/web-pedidos-gateway',
      branch: 'main',
      lastPipeline: 'passed',
      openIssues: 1,
    },
  },
  {
    id: 'wp-api',
    label: 'WP · API',
    kind: 'api',
    status: 'prod',
    domain: 'Aplicaciones',
    owner: 'Equipo GCC',
    description:
      'Servicio de dominio de pedidos. Arma el payload de Sales Order y lo envía a CPI.',
    x: 1420,
    y: 40,
    parentId: 'wp',
    tech: ['.NET 8', 'MediatR'],
    endpoints: [
      {
        id: 'wpapi-pedidos',
        method: 'POST',
        path: '/v1/pedidos',
        target: 'CPI → SAP',
        scope: 'interno',
        avgMs: 1120,
        note: 'Alta de pedido. El body varía según el tipo de pedido.',
        auth: 'Bearer (Azure AD)',
        headers: { 'Content-Type': 'application/json', 'X-Country': 'AR' },
        envUrls: [
          { env: 'Producción', baseUrl: 'https://api.pedidos.grupocepas.com' },
          { env: 'Staging', baseUrl: 'https://api.pedidos.stg.grupocepas.com' },
        ],
        variants: [
          {
            orderType: 'Pedido de venta (ZOR)',
            requestBody:
              '{\n  "tipo": "ZOR",\n  "cliente": "0001002345",\n  "organizacion": "AR10",\n  "items": [\n    { "material": "100023", "cantidad": 12, "um": "CJ" }\n  ],\n  "condicionPago": "Z030"\n}',
            responseBody: '{\n  "pedidoId": "GCC-AR-778812",\n  "estado": "EN_PROCESO"\n}',
          },
          {
            orderType: 'Nota de crédito (ZCR)',
            requestBody:
              '{\n  "tipo": "ZCR",\n  "pedidoOrigen": "GCC-AR-770021",\n  "motivo": "DEV_MERCADERIA",\n  "items": [\n    { "material": "100023", "cantidad": 2, "um": "CJ" }\n  ]\n}',
            note: 'Requiere pedido de origen válido.',
          },
          {
            orderType: 'Bonificación (ZBO)',
            requestBody:
              '{\n  "tipo": "ZBO",\n  "cliente": "0001002345",\n  "campania": "VERANO26",\n  "items": [\n    { "material": "100050", "cantidad": 6, "um": "CJ" }\n  ]\n}',
          },
        ],
      },
      {
        id: 'wpapi-estado',
        method: 'GET',
        path: '/v1/pedidos/:id/estado',
        target: 'CPI → SAP',
        scope: 'interno',
        avgMs: 260,
        auth: 'Bearer (Azure AD)',
        envUrls: [
          { env: 'Producción', baseUrl: 'https://api.pedidos.grupocepas.com' },
          { env: 'Staging', baseUrl: 'https://api.pedidos.stg.grupocepas.com' },
        ],
      },
      {
        id: 'wpapi-credito',
        method: 'GET',
        path: '/v1/clientes/:id/credito',
        target: 'SQL',
        scope: 'interno',
        avgMs: 95,
        note: 'Lee límite de crédito desde la réplica en SQL Server.',
      },
      {
        id: 'wpapi-sap-so',
        method: 'POST',
        path: '/sap/opu/odata/sap/API_SALES_ORDER_SRV/A_SalesOrder',
        target: 'SAP S/4HANA (vía CPI)',
        scope: 'sap',
        avgMs: 840,
        note: 'Llamada real contra la OData de Sales Order de SAP.',
        auth: 'OAuth2 client credentials (CPI)',
        headers: { 'Content-Type': 'application/json', 'x-csrf-token': 'fetch' },
        envUrls: [
          { env: 'Producción', baseUrl: 'https://cpi-prod.grupocepas.com/http' },
          { env: 'Staging', baseUrl: 'https://cpi-stg.grupocepas.com/http' },
        ],
        variants: [
          {
            orderType: 'A_SalesOrder (mapeado desde ZOR)',
            requestBody:
              '{\n  "SalesOrderType": "ZOR",\n  "SoldToParty": "0001002345",\n  "SalesOrganization": "AR10",\n  "to_Item": [\n    { "Material": "100023", "RequestedQuantity": "12" }\n  ]\n}',
            responseBody: '{\n  "d": { "SalesOrder": "0000778812" }\n}',
          },
        ],
      },
    ],
    gitlab: {
      id: 'gl-wp-api',
      path: 'gcc/web-pedidos-api',
      branch: 'release/2.4',
      lastPipeline: 'failed',
      openIssues: 2,
    },
  },

  // rama de inyección secundaria
  {
    id: 'wc',
    label: 'Web de Cobranzas',
    kind: 'interface',
    status: 'staging',
    domain: 'Aplicaciones',
    owner: 'Equipo GCC',
    description: 'Segunda rama de inyección de GCC. Registra pagos y aplica cuentas en SAP FI.',
    x: 1090,
    y: 330,
    parentId: 'gcc',
    tech: ['Next.js', '.NET 8'],
    gitlab: {
      id: 'gl-wc',
      path: 'gcc/web-cobranzas',
      branch: 'develop',
      lastPipeline: 'running',
      openIssues: 5,
    },
  },
  {
    id: 'wc-api',
    label: 'WC · API',
    kind: 'api',
    status: 'staging',
    domain: 'Aplicaciones',
    owner: 'Equipo GCC',
    description: 'API de cobranzas, publica documentos FI vía CPI.',
    x: 1420,
    y: 330,
    parentId: 'wc',
    tech: ['.NET 8'],
    endpoints: [
      { method: 'POST', path: '/v1/pagos', target: 'CPI → SAP FI', avgMs: 640 },
      { method: 'GET', path: '/v1/deuda/:cliente', target: 'SQL', avgMs: 110 },
    ],
  },

  // otras ramas / hijos de GCC
  {
    id: 'smart-panel',
    label: 'Smart Panel',
    kind: 'interface',
    status: 'prod',
    domain: 'Aplicaciones',
    owner: 'Equipo GCC',
    description:
      'Panel de control comercial para supervisores. Tablero de KPIs y aprobación de pedidos. Existe en AR y CL con diferencias de layout.',
    x: 880,
    y: -360,
    parentId: 'gcc',
    country: 'CL',
    tech: ['Next.js', 'Recharts'],
    gitlab: {
      id: 'gl-sp',
      path: 'gcc/smart-panel',
      branch: 'main',
      lastPipeline: 'passed',
      openIssues: 3,
      closedIssues: 9,
      sprint: 'Sprint 24',
      syncedAt: 'hace 8 min',
    },
  },
  {
    id: 'mobile',
    label: 'Mobile (Fuerza de ventas)',
    kind: 'interface',
    status: 'prod',
    domain: 'Aplicaciones',
    owner: 'Equipo Mobile',
    description:
      'App móvil de la fuerza de ventas. Toma pedidos offline y sincroniza contra la API de GCC.',
    x: 1120,
    y: -400,
    parentId: 'gcc',
    country: 'AR',
    tech: ['React Native', 'SQLite', 'Expo'],
    endpoints: [
      {
        id: 'mob-sync',
        method: 'POST',
        path: '/v1/sync/pedidos',
        target: 'WP · Gateway',
        scope: 'interno',
        avgMs: 480,
        note: 'Sincroniza pedidos tomados offline. Reusa el gateway de Web de Pedidos.',
        auth: 'Bearer (Azure AD)',
        envUrls: [
          { env: 'Producción', baseUrl: 'https://gw.pedidos.grupocepas.com' },
          { env: 'Staging', baseUrl: 'https://gw.pedidos.stg.grupocepas.com' },
        ],
        variants: [
          {
            orderType: 'Lote offline',
            requestBody:
              '{\n  "dispositivo": "AND-88123",\n  "pedidos": [\n    { "clienteLocalId": "c-12", "tipo": "ZOR", "items": [ { "material": "100023", "cantidad": 4 } ] }\n  ]\n}',
            note: 'Puede traer varios pedidos por request.',
          },
        ],
      },
      {
        id: 'mob-catalogo',
        method: 'GET',
        path: '/v1/catalogo',
        target: 'SQL',
        scope: 'interno',
        avgMs: 130,
        note: 'Catálogo de productos por país para trabajo offline.',
      },
    ],
    gitlab: {
      id: 'gl-mobile',
      path: 'gcc/mobile-ventas',
      branch: 'release/3.1',
      lastPipeline: 'running',
      openIssues: 6,
      closedIssues: 7,
      sprint: 'Sprint 24',
      syncedAt: 'hace 12 min',
    },
  },
  {
    id: 'autogestion',
    label: 'Autogestión',
    kind: 'interface',
    status: 'staging',
    domain: 'Aplicaciones',
    owner: 'Equipo GCC',
    description:
      'Portal de autogestión para clientes: estado de cuenta, pedidos y reclamos. Piloto en Uruguay.',
    x: 1500,
    y: 480,
    parentId: 'gcc',
    country: 'UY',
    tech: ['Next.js', '.NET 8'],
    gitlab: {
      id: 'gl-auto',
      path: 'gcc/autogestion',
      branch: 'develop',
      lastPipeline: 'passed',
      openIssues: 4,
      closedIssues: 3,
      sprint: 'Sprint 24',
      syncedAt: 'hace 20 min',
    },
  },
  {
    id: 'web-empleados',
    label: 'Web de empleados',
    kind: 'interface',
    status: 'prod',
    domain: 'Aplicaciones',
    owner: 'Equipo RRHH',
    description:
      'Portal interno de empleados: recibos, vacaciones y solicitudes. Integrado a SAP HCM vía CPI.',
    x: 1500,
    y: 640,
    parentId: 'gcc',
    country: 'CL',
    tech: ['Next.js', 'SAP HCM'],
    gitlab: {
      id: 'gl-emp',
      path: 'gcc/web-empleados',
      branch: 'main',
      lastPipeline: 'passed',
      openIssues: 2,
      closedIssues: 12,
      sprint: 'Sprint 24',
      syncedAt: 'hace 8 min',
    },
  },

  // ---------------- DATOS ----------------
  {
    id: 'bigquery',
    label: 'BigQuery',
    kind: 'datastore',
    status: 'prod',
    domain: 'Datos & Analytics',
    owner: 'Data Platform',
    description:
      'Réplica analítica de tablas SAP + datasets derivados. Base de toda la extracción de datos.',
    x: 130,
    y: 470,
    tech: ['BigQuery', 'GCP'],
    volume: '410 tablas · 8.2 TB',
  },
  {
    id: 'builder-comercial',
    label: 'Builder · Comercial',
    kind: 'builder',
    status: 'prod',
    domain: 'Datos & Analytics',
    owner: 'Data Platform',
    description:
      'Transforma tablas crudas de SAP en modelos de negocio (ventas, márgenes, cobertura).',
    x: 480,
    y: 560,
    tech: ['dbt', 'BigQuery SQL'],
    gitlab: {
      id: 'gl-builder',
      path: 'data/builders-comercial',
      branch: 'main',
      lastPipeline: 'passed',
      openIssues: 3,
    },
  },
  {
    id: 'loader-sql',
    label: 'Loader · BQ → SQL',
    kind: 'loader',
    status: 'prod',
    domain: 'Datos & Analytics',
    owner: 'Data Platform',
    description:
      'Job programado que baja los modelos de BigQuery hacia SQL Server para consumo transaccional de GCC.',
    x: 830,
    y: 560,
    tech: ['Python', 'Airflow', 'JDBC'],
    volume: '48 cargas/día',
    environments: [
      { name: 'Producción', server: 'airflow-prod.cepas.gcp', status: 'degradado' },
      { name: 'Desarrollo', server: 'airflow-dev.cepas.gcp', status: 'ok' },
    ],
    gitlab: {
      id: 'gl-loader',
      path: 'data/loaders-sql',
      branch: 'main',
      lastPipeline: 'failed',
      openIssues: 4,
      closedIssues: 6,
      sprint: 'Sprint 24',
      syncedAt: 'hace 15 min',
    },
  },
  {
    id: 'sqlserver',
    label: 'SQL Server · GCC',
    kind: 'datastore',
    status: 'prod',
    domain: 'Datos & Analytics',
    owner: 'Equipo GCC',
    description:
      'Base operativa de GCC. Sirve las consultas de la interfaz sin golpear SAP ni BigQuery.',
    x: 1120,
    y: 470,
    tech: ['SQL Server 2022'],
    volume: '96 tablas',
  },
]

export const ATLAS_EDGES: AtlasEdge[] = [
  // core / externos
  { id: 'e1', source: 'ext-aduana', target: 'web-dispatcher', label: 'SOAP mTLS', direction: 'bidireccional', protocol: 'SOAP', health: 'degradado' },
  { id: 'e2', source: 'web-dispatcher', target: 'sap-s4', label: 'HTTPS interno', direction: 'bidireccional', protocol: 'REST', health: 'ok' },
  { id: 'e3', source: 'ext-courier', target: 'cpi', label: 'REST / API Key', direction: 'bidireccional', protocol: 'REST', health: 'ok' },
  { id: 'e4', source: 'cpi', target: 'sap-s4', label: 'OData / IDoc', direction: 'bidireccional', protocol: 'OData', health: 'ok' },
  { id: 'e5', source: 'sap-s4', target: 'sap-api-salesorder', label: 'expone', direction: 'bidireccional', protocol: 'OData', health: 'ok' },

  // extracción de datos
  { id: 'e6', source: 'sap-s4', target: 'sap-toolkit', label: 'CDC / SLT', direction: 'extraccion', protocol: 'CDC', health: 'ok' },
  { id: 'e7', source: 'sap-toolkit', target: 'bigquery', label: 'replica tablas', direction: 'extraccion', protocol: 'Batch', health: 'ok' },
  { id: 'e8', source: 'bigquery', target: 'builder-comercial', label: 'transforma', direction: 'extraccion', protocol: 'Batch', health: 'ok' },
  { id: 'e9', source: 'builder-comercial', target: 'loader-sql', label: 'modelos listos', direction: 'extraccion', protocol: 'Batch', health: 'ok' },
  { id: 'e10', source: 'loader-sql', target: 'sqlserver', label: 'carga JDBC', direction: 'extraccion', protocol: 'JDBC', health: 'degradado' },
  { id: 'e11', source: 'sqlserver', target: 'gcc', label: 'lee catálogo y stock', direction: 'extraccion', protocol: 'JDBC', health: 'ok' },

  // inyección de datos
  { id: 'e12', source: 'gcc', target: 'wp', label: 'rama', direction: 'inyeccion', protocol: 'REST', health: 'ok' },
  { id: 'e13', source: 'gcc', target: 'wc', label: 'rama', direction: 'inyeccion', protocol: 'REST', health: 'ok' },
  { id: 'e14', source: 'wp', target: 'wp-front', label: 'componente', direction: 'inyeccion', protocol: 'REST', health: 'ok' },
  { id: 'e15', source: 'wp-front', target: 'wp-gw', label: 'HTTPS + JWT', direction: 'inyeccion', protocol: 'REST', health: 'ok' },
  { id: 'e16', source: 'wp-gw', target: 'wp-api', label: 'ruteo', direction: 'inyeccion', protocol: 'REST', health: 'ok' },
  { id: 'e17', source: 'wp-api', target: 'cpi', label: 'POST /v1/pedidos', direction: 'inyeccion', protocol: 'REST', health: 'ok' },
  { id: 'e18', source: 'cpi', target: 'sap-api-salesorder', label: 'POST A_SalesOrder', direction: 'inyeccion', protocol: 'OData', health: 'ok' },
  { id: 'e19', source: 'wc', target: 'wc-api', label: 'componente', direction: 'inyeccion', protocol: 'REST', health: 'ok' },
  { id: 'e20', source: 'wc-api', target: 'cpi', label: 'POST /v1/pagos', direction: 'inyeccion', protocol: 'REST', health: 'caido' },
  { id: 'e21', source: 'wp-api', target: 'sqlserver', label: 'lee crédito', direction: 'extraccion', protocol: 'JDBC', health: 'ok' },

  // ramas nuevas de GCC
  { id: 'e22', source: 'gcc', target: 'smart-panel', label: 'rama', direction: 'inyeccion', protocol: 'REST', health: 'ok' },
  { id: 'e23', source: 'gcc', target: 'mobile', label: 'rama', direction: 'inyeccion', protocol: 'REST', health: 'ok' },
  { id: 'e24', source: 'gcc', target: 'autogestion', label: 'rama', direction: 'inyeccion', protocol: 'REST', health: 'ok' },
  { id: 'e25', source: 'gcc', target: 'web-empleados', label: 'rama', direction: 'inyeccion', protocol: 'REST', health: 'ok' },
  { id: 'e26', source: 'mobile', target: 'wp-gw', label: 'usa gateway', direction: 'inyeccion', protocol: 'REST', health: 'ok' },
  { id: 'e27', source: 'web-empleados', target: 'cpi', label: 'HCM vía CPI', direction: 'bidireccional', protocol: 'OData', health: 'ok' },
]

export const ATLAS_ISSUES: GitlabIssue[] = [
  { id: 'i1', iid: 412, title: 'Timeout intermitente al postear pedidos > 40 líneas', kind: 'incidente', severity: 'bloqueante', state: 'en_curso', sprint: 'Sprint 24', assignee: 'M. Duarte', project: 'gcc/web-pedidos-api', nodeId: 'wp-api' },
  { id: 'i2', iid: 409, title: 'Validar stock antes de habilitar el botón Confirmar', kind: 'mejora', severity: 'media', state: 'abierto', sprint: 'Sprint 24', assignee: 'L. Arce', project: 'gcc/web-pedidos-front', nodeId: 'wp-front' },
  { id: 'i3', iid: 401, title: 'Mapeo de condiciones de precio pierde descuento escalonado', kind: 'fix', severity: 'alta', state: 'review', sprint: 'Sprint 24', assignee: 'J. Pérez', project: 'integraciones/cpi-iflows', nodeId: 'cpi' },
  { id: 'i4', iid: 398, title: 'Loader BQ→SQL falla si la partición del día está vacía', kind: 'fix', severity: 'alta', state: 'en_curso', sprint: 'Sprint 24', assignee: 'S. Rivas', project: 'data/loaders-sql', nodeId: 'loader-sql' },
  { id: 'i5', iid: 395, title: 'Agregar reintento exponencial en el gateway', kind: 'mejora', severity: 'media', state: 'abierto', sprint: 'Sprint 24', assignee: 'M. Duarte', project: 'gcc/web-pedidos-gateway', nodeId: 'wp-gw' },
  { id: 'i6', iid: 390, title: 'Builder comercial: margen duplicado en devoluciones', kind: 'fix', severity: 'alta', state: 'abierto', sprint: 'Sprint 24', assignee: 'S. Rivas', project: 'data/builders-comercial', nodeId: 'builder-comercial' },
  { id: 'i7', iid: 388, title: 'Web de Cobranzas: certificado de CPI vencido en staging', kind: 'incidente', severity: 'bloqueante', state: 'abierto', sprint: 'Sprint 24', assignee: 'J. Pérez', project: 'gcc/web-cobranzas', nodeId: 'wc' },
  { id: 'i8', iid: 385, title: 'Documentar endpoints de GCC en el catálogo interno', kind: 'mejora', severity: 'baja', state: 'abierto', sprint: 'Sprint 24', assignee: 'C. Molina', project: 'gcc/gcc-platform', nodeId: 'gcc' },
  { id: 'i9', iid: 380, title: 'Migrar Portal Aduana de SOAP a REST vía CPI', kind: 'mejora', severity: 'media', state: 'abierto', sprint: 'Backlog', assignee: 'Sin asignar', project: 'integraciones/cpi-iflows', nodeId: 'ext-aduana' },
  { id: 'i10', iid: 377, title: 'Replicar tabla VBRP faltante en BigQuery', kind: 'fix', severity: 'media', state: 'cerrado', sprint: 'Sprint 23', assignee: 'S. Rivas', project: 'data/builders-comercial', nodeId: 'sap-toolkit' },
  { id: 'i11', iid: 415, title: 'Cache de crédito de cliente en SQL con TTL de 5 min', kind: 'mejora', severity: 'media', state: 'abierto', sprint: 'Sprint 24', assignee: 'L. Arce', project: 'gcc/web-pedidos-api', nodeId: 'wp-api' },
  { id: 'i12', iid: 416, title: 'GCC: paginación rota en listado de pedidos', kind: 'fix', severity: 'alta', state: 'en_curso', sprint: 'Sprint 24', assignee: 'C. Molina', project: 'gcc/gcc-platform', nodeId: 'gcc' },
  { id: 'i13', iid: 420, title: 'Smart Panel: KPI de cobertura no refleja devoluciones', kind: 'fix', severity: 'media', state: 'abierto', sprint: 'Sprint 24', assignee: 'L. Arce', project: 'gcc/smart-panel', nodeId: 'smart-panel' },
  { id: 'i14', iid: 421, title: 'Mobile: pedidos offline se duplican al reconectar', kind: 'incidente', severity: 'bloqueante', state: 'en_curso', sprint: 'Sprint 24', assignee: 'C. Molina', project: 'gcc/mobile-ventas', nodeId: 'mobile' },
  { id: 'i15', iid: 422, title: 'Mobile: soportar login biométrico', kind: 'mejora', severity: 'baja', state: 'abierto', sprint: 'Sprint 24', assignee: 'Sin asignar', project: 'gcc/mobile-ventas', nodeId: 'mobile' },
  { id: 'i16', iid: 423, title: 'Autogestión UY: adaptar comprobantes a normativa DGI', kind: 'mejora', severity: 'alta', state: 'abierto', sprint: 'Sprint 24', assignee: 'S. Rivas', project: 'gcc/autogestion', nodeId: 'autogestion' },
  { id: 'i17', iid: 424, title: 'Web de empleados: recibo PDF no abre en Safari', kind: 'fix', severity: 'media', state: 'review', sprint: 'Sprint 24', assignee: 'J. Pérez', project: 'gcc/web-empleados', nodeId: 'web-empleados' },
]
