import type { AtlasEdge, AtlasNode, GitlabIssue } from './atlas-types'

/**
 * Primer mapa REAL de integraciones de Grupo Cepas.
 * Fuente: descripción funcional validada por Pamela + modelo Archi Cepas General.
 * Se mantiene deliberadamente parcial: no inventamos relaciones de las interfaces
 * que todavía no fueron detalladas.
 */
export const ATLAS_NODES: AtlasNode[] = [
  {
    id: 'sap-s4',
    label: 'SAP S/4HANA RISE',
    kind: 'erp',
    status: 'prod',
    domain: 'Core SAP',
    owner: 'SAP / Basis',
    description: 'ERP central. Se integra con CPI, Web Dispatcher, ODP para Google BigQuery y el servidor de interfaces.',
    x: 40, y: 0,
    tech: ['SAP S/4HANA RISE'],
  },
  {
    id: 'cpi',
    label: 'SAP CPI',
    kind: 'middleware',
    status: 'prod',
    domain: 'Integración',
    owner: 'Integraciones',
    description: 'Middleware de integración entre SAP y aplicaciones/interfaces. Conecta Identity, KETAN, CDL, CAOLIX, DMP, ARCA y APIs estándar usadas por GCC.',
    x: 560, y: 0,
    tech: ['SAP Integration Suite / CPI'],
  },
  {
    id: 'web-dispatcher',
    label: 'SAP Web Dispatcher',
    kind: 'dispatcher',
    status: 'prod',
    domain: 'Core SAP',
    owner: 'SAP / Basis',
    description: 'Punto de entrada HTTP(S) hacia SAP para integraciones que no pasan por CPI. EBuyPlace se conecta por este camino.',
    x: 300, y: 720,
    tech: ['SAP Web Dispatcher'],
  },
  {
    id: 'sap-toolkit',
    label: 'S/4 HANA ODP · Toolkit Google BigQuery',
    kind: 'loader',
    status: 'prod',
    domain: 'Datos & Analytics',
    owner: 'Data',
    description: 'Replica y extrae tablas de SAP hacia BigQuery mediante ODP/Toolkit de Google.',
    x: 300, y: 1080,
    tech: ['ODP', 'Google Cloud Toolkit for SAP'],
  },
  {
    id: 'server-interfaces',
    label: 'Server interfaces.cepas.net',
    kind: 'server',
    status: 'prod',
    domain: 'Integración',
    owner: 'Infraestructura',
    description: 'Servidor intermedio de archivos y procesos para integraciones como MACRO, Visma y COT.',
    x: 300, y: 820,
    tech: ['Linux/Windows file integration'],
  },
  {
    id: 'bigquery',
    label: 'Google BigQuery',
    kind: 'datastore',
    status: 'prod',
    domain: 'Datos & Analytics',
    owner: 'Data',
    description: 'Destino de replicación de datos de SAP y origen de cargas hacia SQL Server.',
    x: 560, y: 1080,
    tech: ['Google BigQuery'],
  },
  {
    id: 'sqlserver',
    label: 'SQL Server',
    kind: 'datastore',
    status: 'prod',
    domain: 'Datos & Analytics',
    owner: 'Data / Aplicaciones',
    description: 'Persistencia operacional alimentada desde BigQuery mediante loaders y builders.',
    x: 1280, y: 1080,
    tech: ['SQL Server'],
  },
  {
    id: 'loaders',
    label: 'Loaders BQ → SQL',
    kind: 'loader',
    status: 'prod',
    domain: 'Datos & Analytics',
    owner: 'Data',
    description: 'Procesos que leen datos desde BigQuery y los preparan/cargan para consumo en SQL Server.',
    x: 800, y: 1080,
    tech: ['Loaders'],
  },
  {
    id: 'builders',
    label: 'Builders',
    kind: 'builder',
    status: 'prod',
    domain: 'Datos & Analytics',
    owner: 'Data',
    description: 'Procesos de preparación y construcción de modelos/tablas para consumo por otros desarrollos y SQL Server.',
    x: 1040, y: 1080,
    tech: ['Builders'],
  },

  // Interfaces principales
  {
    id: 'identity',
    label: 'Identity',
    kind: 'microservice',
    status: 'prod',
    domain: 'Aplicaciones',
    owner: 'Aplicaciones',
    description: 'Servicios de identidad conectados con CPI y usados por otros desarrollos.',
    x: 820, y: 140,
    tech: ['Microservices'],
  },
  {
    id: 'ketan',
    label: 'KETAN',
    kind: 'interface',
    status: 'prod',
    domain: 'Aplicaciones',
    owner: 'Operaciones / Integraciones',
    description: 'Integración KETAN. Interfaces PP-01 KETAN IDA y PP-02 KETAN VUELTA.',
    x: 820, y: 230,
    tech: ['Gateway', 'SQL Server'],
  },
  {
    id: 'cdl',
    label: 'CDL · Consumo en Línea',
    kind: 'interface',
    status: 'prod',
    domain: 'Aplicaciones',
    owner: 'Operaciones / Integraciones',
    description: 'Consumo en Línea. Integración conectada a SAP mediante CPI.',
    x: 820, y: 320,
  },
  {
    id: 'caolix',
    label: 'CAOLIX',
    kind: 'external',
    status: 'prod',
    domain: 'Integración',
    owner: 'Finanzas',
    description: 'Web externa para rendición de gastos de empleados. Las rendiciones llegan por CPI y se contabilizan en SAP. Código FI-10.',
    x: 820, y: 410,
    country: 'AR',
  },
  {
    id: 'dmp',
    label: 'DMP · Datos Maestros de Personal',
    kind: 'interface',
    status: 'prod',
    domain: 'Aplicaciones',
    owner: 'Capital Humano',
    description: 'Front para actualización de datos personales de empleados. Tiene Front, Gateway, API y SQL. Capital Humano ejecuta luego un programa SAP que incorpora la información.',
    x: 820, y: 500,
    country: 'AR',
  },
  {
    id: 'dmp-front',
    label: 'DMP · Front',
    kind: 'front',
    status: 'prod',
    domain: 'Aplicaciones',
    owner: 'Capital Humano',
    description: 'Frontend de DMP.',
    x: 1060, y: 450,
    parentId: 'dmp',
  },
  {
    id: 'dmp-gw',
    label: 'DMP · Gateway',
    kind: 'gateway',
    status: 'prod',
    domain: 'Aplicaciones',
    owner: 'Capital Humano',
    description: 'Gateway de DMP.',
    x: 1060, y: 520,
    parentId: 'dmp',
    environments: [
      { name: 'Desarrollo', server: 'cepaslabo2:8027', url: 'http://cepaslabo2:8027/Gw.DMP_DEV', status: 'ok' },
      { name: 'QA', server: 'cepaslabo2:8027', url: 'http://cepaslabo2:8027/Gw.DMP/', status: 'ok' },
    ],
  },
  {
    id: 'dmp-api',
    label: 'DMP · API',
    kind: 'api',
    status: 'prod',
    domain: 'Aplicaciones',
    owner: 'Capital Humano',
    description: 'API de DMP.',
    x: 1300, y: 520,
    parentId: 'dmp',
  },
  {
    id: 'dmp-sql',
    label: 'DMP · SQL',
    kind: 'datastore',
    status: 'prod',
    domain: 'Datos & Analytics',
    owner: 'Capital Humano',
    description: 'Base SQL de DMP.',
    x: 1300, y: 590,
    parentId: 'dmp',
  },
  {
    id: 'arca',
    label: 'ARCA · Factura Electrónica',
    kind: 'external',
    status: 'prod',
    domain: 'Integración',
    owner: 'Fiscal / SAP',
    description: 'Integración de Factura Electrónica Doméstica y Factura Electrónica de Exportación.',
    x: 820, y: 590,
    country: 'AR',
  },
  {
    id: 'ebuyplace',
    label: 'EBuyPlace',
    kind: 'external',
    status: 'prod',
    domain: 'Integración',
    owner: 'Compras',
    description: 'Interfaz conectada a SAP a través de Web Dispatcher. Códigos FI-01 y MM-04.',
    x: 560, y: 720,
  },
  {
    id: 'macro',
    label: 'MACRO AR',
    kind: 'external',
    status: 'prod',
    domain: 'Integración',
    owner: 'Finanzas',
    description: 'Integración bancaria por SFTP usando el servidor de interfaces. Código FI-07.',
    x: 560, y: 790,
    country: 'AR',
  },
  {
    id: 'visma',
    label: 'Visma',
    kind: 'external',
    status: 'prod',
    domain: 'Integración',
    owner: 'Capital Humano',
    description: 'Integración por SFTP usando el servidor de interfaces. Código HCM-01.',
    x: 560, y: 860,
  },
  {
    id: 'cot',
    label: 'COT · ARBA',
    kind: 'external',
    status: 'prod',
    domain: 'Integración',
    owner: 'Logística / Fiscal',
    description: 'Servicio COT hacia ARBA mediante archivos y servidor de interfaces. Código SD-21.',
    x: 560, y: 930,
    country: 'AR',
  },
  {
    id: 'intouch',
    label: 'Intouch',
    kind: 'interface',
    status: 'prod',
    domain: 'Aplicaciones',
    owner: 'Compras',
    description: 'Interfaz manual: un archivo se descarga desde una transacción Fiori y otro se sube mediante otra transacción Fiori. Código MM-03.',
    x: 40, y: -280,
  },
  {
    id: 'balanza-burzaco',
    label: 'Balanza Burzaco',
    kind: 'interface',
    status: 'prod',
    domain: 'Aplicaciones',
    owner: 'Logística',
    description: 'Desde Fiori levanta el pesaje de la balanza física de camiones. Código TM-02.',
    x: 40, y: -370,
    country: 'AR',
  },
  {
    id: 'balanza-mendoza',
    label: 'Balanza Mendoza',
    kind: 'interface',
    status: 'prod',
    domain: 'Aplicaciones',
    owner: 'Logística',
    description: 'Desde Fiori levanta el pesaje de la balanza física de camiones. Código TM-03.',
    x: 300, y: -370,
    country: 'AR',
  },
  {
    id: 'citi',
    label: 'CITI',
    kind: 'interface',
    status: 'prod',
    domain: 'Aplicaciones',
    owner: 'Finanzas / SAP',
    description: 'Desarrollo en SAP para generación de cheques destinados al pago a proveedores. Códigos FI-05 y FI-06.',
    x: 300, y: -280,
  },
  {
    id: 'tec',
    label: 'TEC · Estado de Camiones',
    kind: 'interface',
    status: 'prod',
    domain: 'Aplicaciones',
    owner: 'Logística',
    description: 'Web que muestra estado de camiones. Parte de una tabla Z SAP replicada en BigQuery, luego cargada en SQL y consumida por la web. Código TM-01.',
    x: 1520, y: 1080,
    country: 'AR',
  },
  {
    id: 'gcc',
    label: 'GCC · Gestión Comercial Cepas',
    kind: 'interface',
    status: 'prod',
    domain: 'Aplicaciones',
    owner: 'Comercial',
    description: 'Gestión Comercial Cepas. Código SD-12. La cadena técnica pasa por Gateway y API de Cepas, CPI y luego APIs estándar de SAP.',
    x: 1300, y: -90,
    country: 'AR',
  },
  {
    id: 'gcc-gw',
    label: 'GW Cepas · GCC',
    kind: 'gateway',
    status: 'prod',
    domain: 'Aplicaciones',
    owner: 'Comercial / Integraciones',
    description: 'Gateway de Cepas utilizado por GCC antes de la API de negocio.',
    x: 1060, y: -90,
    parentId: 'gcc',
    environments: [
      { name: 'Desarrollo', server: 'apisdev.grupocepas.com', url: 'https://apisdev.grupocepas.com/Gw.GCC.SmartPanel_DEV/', status: 'ok' },
      { name: 'QA', server: 'apisdev.grupocepas.com', url: 'https://apisdev.grupocepas.com/Gw.GCC.SmartPanel_TEST', status: 'ok' },
    ],
    country: 'AR',
  },
  {
    id: 'gcc-api',
    label: 'API Cepas · GCC',
    kind: 'api',
    status: 'prod',
    domain: 'Aplicaciones',
    owner: 'Comercial / Integraciones',
    description: 'API de Cepas utilizada por GCC. Desde aquí la integración continúa hacia CPI.',
    x: 820, y: -90,
    parentId: 'gcc',
    country: 'AR',
  },

  // Catálogo técnico conocido de Gateways / APIs Cepas.
  // Cargado desde inventario visual compartido por Pamela. Los ambientes se consolidan
  // en un único nodo lógico; no se duplica el nodo por DEV/QAS.
  {
    id: 'gw-sap4hana',
    label: 'Gw.Sap4Hana',
    kind: 'gateway',
    status: 'prod',
    domain: 'Aplicaciones',
    owner: 'Integraciones',
    description: 'Gateway Cepas hacia SAP S/4HANA. Inventario técnico conocido.',
    x: 1120, y: -220,
    tech: ['Gateway', 'REST'],
    environments: [
      { name: 'Desarrollo', server: 'apisdev.grupocepas.com', url: 'https://apisdev.grupocepas.com/Gw.Sap4hana_dev', status: 'ok' },
      { name: 'QA', server: 'apisdev.grupocepas.com', url: 'https://apisdev.grupocepas.com/Gw.Sap4hana_TEST', status: 'ok' },
    ],
  },
  {
    id: 'gw-gcc-smartpanel',
    label: 'Gw.GCC.SmartPanel',
    kind: 'gateway',
    status: 'prod',
    domain: 'Aplicaciones',
    owner: 'Comercial / Integraciones',
    description: 'Gateway técnico de GCC SmartPanel.',
    x: 1120, y: -140,
    parentId: 'gcc',
    tech: ['Gateway', 'REST'],
    environments: [
      { name: 'Desarrollo', server: 'apisdev.grupocepas.com', url: 'https://apisdev.grupocepas.com/Gw.GCC.SmartPanel_DEV/', status: 'ok' },
      { name: 'QA', server: 'apisdev.grupocepas.com', url: 'https://apisdev.grupocepas.com/Gw.GCC.SmartPanel_TEST', status: 'ok' },
    ],
  },
  {
    id: 'gw-mobile-gc',
    label: 'Gw.Mobile.GC',
    kind: 'gateway',
    status: 'prod',
    domain: 'Aplicaciones',
    owner: 'Comercial / Integraciones',
    description: 'Gateway técnico Mobile GC.',
    x: 1120, y: -60,
    parentId: 'gcc',
    tech: ['Gateway', 'REST'],
    environments: [
      { name: 'Desarrollo', server: 'apisdev.grupocepas.com', url: 'https://apisdev.grupocepas.com/Gw.Mobile.GC_DEV', status: 'ok' },
      { name: 'QA', server: 'apisdev.grupocepas.com', url: 'https://apisdev.grupocepas.com/Gw.GCC.SmartPanel', status: 'ok' },
    ],
  },
  {
    id: 'gw-web-empleados',
    label: 'Gw.Web.Empleados',
    kind: 'gateway',
    status: 'prod',
    domain: 'Aplicaciones',
    owner: 'Capital Humano / Integraciones',
    description: 'Gateway técnico de Web Empleados.',
    x: 1120, y: 20,
    tech: ['Gateway', 'REST'],
    environments: [
      { name: 'Desarrollo', server: 'cepasservices4k:8027', url: 'http://cepasservices4k:8027/Gw.Web.Empleados', status: 'ok' },
      { name: 'QA', server: 'cepasservices4k:8027', url: 'http://cepasservices4k:8027/Gw.Web.Empleados_TEST', status: 'ok' },
    ],
  },
  {
    id: 'gw-web-pedidos',
    label: 'Gw.WebPedidos',
    kind: 'gateway',
    status: 'prod',
    domain: 'Aplicaciones',
    owner: 'Comercial / Integraciones',
    description: 'Gateway técnico de Web Pedidos.',
    x: 1120, y: 100,
    parentId: 'gcc',
    tech: ['Gateway', 'REST'],
    environments: [
      { name: 'Desarrollo', server: 'apisdev.grupocepas.com', url: 'https://apisdev.grupocepas.com/Gw.WebPedidos', status: 'ok' },
      { name: 'QA', server: 'apis.grupocepas.com', url: 'https://apis.grupocepas.com/Gw.Sap4Hana', status: 'ok' },
    ],
  },
  {
    id: 'api-consumo-linea',
    label: 'Api.ConsumoLinea',
    kind: 'api',
    status: 'prod',
    domain: 'Aplicaciones',
    owner: 'Operaciones / Integraciones',
    description: 'API técnica de Consumo en Línea.',
    x: 1040, y: 300,
    parentId: 'cdl',
    tech: ['API', 'REST'],
  },
  {
    id: 'api-employee',
    label: 'Api.Employee',
    kind: 'api',
    status: 'prod',
    domain: 'Aplicaciones',
    owner: 'Capital Humano / Integraciones',
    description: 'API técnica de Employee.',
    x: 1040, y: 380,
    tech: ['API', 'REST'],
    environments: [
      { name: 'Desarrollo', server: 'cepaslabo2:9020', url: 'http://cepaslabo2:9020/Cepas.Employee_Dev', status: 'ok' },
    ],
  },
  {
    id: 'api-gvd',
    label: 'API.GVD',
    kind: 'api',
    status: 'prod',
    domain: 'Aplicaciones',
    owner: 'Pendiente',
    description: 'API técnica detectada en inventario. Asociación funcional pendiente de confirmar.',
    x: 1040, y: 460,
    tech: ['API'],
  },
  {
    id: 'api-ketan',
    label: 'Api.Ketan',
    kind: 'api',
    status: 'prod',
    domain: 'Aplicaciones',
    owner: 'Operaciones / Integraciones',
    description: 'API técnica de KETAN.',
    x: 1040, y: 540,
    parentId: 'ketan',
    tech: ['API', 'REST'],
    environments: [
      { name: 'Desarrollo', server: 'cepaslabo2:9020', url: 'http://cepaslabo2:9020/Cepas.Ketan/', status: 'ok' },
    ],
  },
  {
    id: 'api-orders-v2',
    label: 'Api.Orders_V2',
    kind: 'api',
    status: 'prod',
    domain: 'Aplicaciones',
    owner: 'Comercial / Integraciones',
    description: 'API técnica Orders V2 de GCC.',
    x: 1040, y: 620,
    parentId: 'gcc',
    tech: ['API', 'REST'],
  },
  {
    id: 'api-product-image',
    label: 'Api.ProductImage',
    kind: 'api',
    status: 'prod',
    domain: 'Aplicaciones',
    owner: 'Comercial / Integraciones',
    description: 'API técnica de imágenes de producto.',
    x: 1040, y: 700,
    parentId: 'gcc',
    tech: ['API', 'REST'],
  },
  {
    id: 'cepas-order-api',
    label: 'Cepas.Order.Api',
    kind: 'api',
    status: 'prod',
    domain: 'Aplicaciones',
    owner: 'Comercial / Integraciones',
    description: 'API técnica de órdenes Cepas.',
    x: 1040, y: 780,
    parentId: 'gcc',
    tech: ['API', 'REST'],
  },

  // APIs estándar SAP usadas por GCC
  {
    id: 'api-sales-order',
    label: 'API Sales Order',
    kind: 'api',
    status: 'prod',
    domain: 'Core SAP',
    owner: 'SAP',
    description: 'API estándar de SAP utilizada por GCC para pedidos de venta.',
    x: 300, y: -180,
    parentId: 'sap-s4',
    tech: ['OData'],
  },
  {
    id: 'api-sales-order-simulate',
    label: 'API Sales Order Simulate',
    kind: 'api',
    status: 'prod',
    domain: 'Core SAP',
    owner: 'SAP',
    description: 'API estándar SAP para simulación de pedidos de venta usada por GCC.',
    x: 300, y: -90,
    parentId: 'sap-s4',
    tech: ['OData'],
  },
  {
    id: 'api-customer-return',
    label: 'API Customer Return',
    kind: 'api',
    status: 'prod',
    domain: 'Core SAP',
    owner: 'SAP',
    description: 'API estándar SAP para devoluciones de cliente usada por GCC.',
    x: 300, y: 0,
    parentId: 'sap-s4',
    tech: ['OData'],
  },
  {
    id: 'api-customer-return-simulate',
    label: 'API Customer Return Simulate',
    kind: 'api',
    status: 'prod',
    domain: 'Core SAP',
    owner: 'SAP',
    description: 'API estándar SAP para simulación de devoluciones de cliente usada por GCC.',
    x: 300, y: 90,
    parentId: 'sap-s4',
    tech: ['OData'],
  },
]

export const ATLAS_EDGES: AtlasEdge[] = [
  { id: 'sap-cpi', source: 'sap-s4', target: 'cpi', label: 'integración SAP', direction: 'bidireccional', protocol: 'OData', health: 'ok' },
  { id: 'sap-webdispatcher', source: 'sap-s4', target: 'web-dispatcher', label: 'HTTP(S)', direction: 'bidireccional', protocol: 'REST', health: 'ok' },
  { id: 'sap-odp', source: 'sap-s4', target: 'sap-toolkit', label: 'ODP · extracción/replicación', direction: 'extraccion', protocol: 'CDC', health: 'ok' },
  { id: 'sap-server', source: 'sap-s4', target: 'server-interfaces', label: 'archivos / jobs', direction: 'bidireccional', protocol: 'Batch', health: 'ok' },

  { id: 'odp-bq', source: 'sap-toolkit', target: 'bigquery', label: 'replica tablas SAP', direction: 'extraccion', protocol: 'CDC', health: 'ok' },
  { id: 'bq-loaders', source: 'bigquery', target: 'loaders', label: 'lectura / extracción', direction: 'extraccion', protocol: 'Batch', health: 'ok' },
  { id: 'loaders-builders', source: 'loaders', target: 'builders', label: 'preparación', direction: 'extraccion', protocol: 'Batch', health: 'ok' },
  { id: 'builders-sql', source: 'builders', target: 'sqlserver', label: 'carga SQL', direction: 'extraccion', protocol: 'JDBC', health: 'ok' },
  { id: 'sql-tec', source: 'sqlserver', target: 'tec', label: 'consulta estado camiones', direction: 'extraccion', protocol: 'JDBC', health: 'ok' },

  { id: 'cpi-identity', source: 'cpi', target: 'identity', label: 'integración', direction: 'bidireccional', protocol: 'REST', health: 'ok' },
  { id: 'cpi-ketan', source: 'cpi', target: 'ketan', label: 'PP-01 / PP-02', direction: 'bidireccional', protocol: 'REST', health: 'ok' },
  { id: 'cpi-cdl', source: 'cpi', target: 'cdl', label: 'Consumo en Línea', direction: 'bidireccional', protocol: 'REST', health: 'ok' },
  { id: 'cpi-caolix', source: 'cpi', target: 'caolix', label: 'FI-10 · rendiciones', direction: 'bidireccional', protocol: 'REST', health: 'ok' },
  { id: 'cpi-dmp', source: 'cpi', target: 'dmp', label: 'HCM-05', direction: 'bidireccional', protocol: 'REST', health: 'ok' },
  { id: 'cpi-arca', source: 'cpi', target: 'arca', label: 'Factura electrónica', direction: 'bidireccional', protocol: 'SOAP', health: 'ok' },

  { id: 'web-ebuy', source: 'web-dispatcher', target: 'ebuyplace', label: 'FI-01 / MM-04', direction: 'bidireccional', protocol: 'REST', health: 'ok' },

  { id: 'server-macro', source: 'server-interfaces', target: 'macro', label: 'FI-07 · SFTP', direction: 'bidireccional', protocol: 'SFTP', health: 'ok' },
  { id: 'server-visma', source: 'server-interfaces', target: 'visma', label: 'HCM-01 · SFTP', direction: 'bidireccional', protocol: 'SFTP', health: 'ok' },
  { id: 'server-cot', source: 'server-interfaces', target: 'cot', label: 'SD-21 · archivos', direction: 'bidireccional', protocol: 'SFTP', health: 'ok' },

  { id: 'sap-intouch', source: 'sap-s4', target: 'intouch', label: 'MM-03 · archivo Fiori manual', direction: 'bidireccional', protocol: 'Manual', health: 'ok' },
  { id: 'sap-bal-burzaco', source: 'sap-s4', target: 'balanza-burzaco', label: 'TM-02 · Fiori', direction: 'inyeccion', protocol: 'REST', health: 'ok' },
  { id: 'sap-bal-mendoza', source: 'sap-s4', target: 'balanza-mendoza', label: 'TM-03 · Fiori', direction: 'inyeccion', protocol: 'REST', health: 'ok' },
  { id: 'sap-citi', source: 'sap-s4', target: 'citi', label: 'FI-05 / FI-06', direction: 'inyeccion', protocol: 'Batch', health: 'ok' },

  { id: 'dmp-front-gw', source: 'dmp-front', target: 'dmp-gw', label: 'frontend → gateway', direction: 'inyeccion', protocol: 'REST', health: 'ok' },
  { id: 'dmp-gw-api', source: 'dmp-gw', target: 'dmp-api', label: 'gateway → api', direction: 'inyeccion', protocol: 'REST', health: 'ok' },
  { id: 'dmp-api-sql', source: 'dmp-api', target: 'dmp-sql', label: 'persistencia', direction: 'inyeccion', protocol: 'JDBC', health: 'ok' },
  { id: 'dmp-sap', source: 'dmp-sql', target: 'sap-s4', label: 'programa SAP incorpora datos', direction: 'inyeccion', protocol: 'Batch', health: 'ok' },

  { id: 'gw-gcc-api', source: 'gcc-gw', target: 'gcc-api', label: 'Gateway → API Cepas', direction: 'bidireccional', protocol: 'REST', health: 'ok' },
  { id: 'gcc-api-cpi', source: 'gcc-api', target: 'cpi', label: 'API Cepas → CPI', direction: 'bidireccional', protocol: 'REST', health: 'ok' },
  { id: 'cpi-api-so', source: 'cpi', target: 'api-sales-order', label: 'Sales Order', direction: 'bidireccional', protocol: 'OData', health: 'ok' },
  { id: 'cpi-api-so-sim', source: 'cpi', target: 'api-sales-order-simulate', label: 'Sales Order Simulate', direction: 'bidireccional', protocol: 'OData', health: 'ok' },
  { id: 'cpi-api-cr', source: 'cpi', target: 'api-customer-return', label: 'Customer Return', direction: 'bidireccional', protocol: 'OData', health: 'ok' },
  { id: 'cpi-api-cr-sim', source: 'cpi', target: 'api-customer-return-simulate', label: 'Customer Return Simulate', direction: 'bidireccional', protocol: 'OData', health: 'ok' },
  { id: 'api-so-sap', source: 'api-sales-order', target: 'sap-s4', label: 'API SAP → S/4', direction: 'bidireccional', protocol: 'OData', health: 'ok' },
  { id: 'api-so-sim-sap', source: 'api-sales-order-simulate', target: 'sap-s4', label: 'API SAP → S/4', direction: 'bidireccional', protocol: 'OData', health: 'ok' },
  { id: 'api-cr-sap', source: 'api-customer-return', target: 'sap-s4', label: 'API SAP → S/4', direction: 'bidireccional', protocol: 'OData', health: 'ok' },
  { id: 'api-cr-sim-sap', source: 'api-customer-return-simulate', target: 'sap-s4', label: 'API SAP → S/4', direction: 'bidireccional', protocol: 'OData', health: 'ok' },
]

/**
 * Los issues demo se eliminan del mapa real.
 * Se volverán a incorporar únicamente desde fuentes reales (GitLab / incidentes / documentación).
 */
export const ATLAS_ISSUES: GitlabIssue[] = []
